### ISSUE TITLE
Desarrollo de interfaz

### ISSUE THREAD

**Issue by ekzGuille** [ekzGuille/PhantomLimb-RA#8]

**Comment by amareca** [comment]
- Crear una nueva **Scene** para el menú principal.

**Comment by ekzGuille** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Desarrollar interfaz de la aplicación](https://trello.com/c/G3bQuYUk/18-desarrollar-interfaz-de-la-aplicaci%C3%B3n)
